#!/bin/bash
# Small setup script for dotfiles repo.
# Usage: curl --silent https://raw.githubusercontent.com/reap2sow1/dotfiles/main/install | bash
set -e
PWD="$(pwd)"
PROGRAM_NAME="install"
PROFILE_FILE_NAME=".profile" # assuming .profile is ALWAYS '.profile'
TEMP_DIR_NAME="${PROGRAM_NAME}-temp"
PROFILE_REMOTE_URL='https://raw.githubusercontent.com/reap2sow1/dotfiles/main/.profile'
DOTFILES_TO_INCLUDE_FOR_LINKING=(
    .bashrc
    .profile
    .bash_profile
    .gitignore
    .gitconfig
)

if [ "$PWD" != "$HOME" ]; then
    # main reason is to avoid filemode permissions issues
    echo "${PROGRAM_NAME}: re-run this script in $HOME (assuming you haven't changed this!), to run this correctly"
    exit 1
fi

if [ -z "$(which curl)" ]; then
    echo "${PROGRAM_NAME}: curl cannot be found on the PATH!"
    exit 1
fi

if [ -z "$(which git)" ]; then
    echo "${PROGRAM_NAME}: git cannot be found on the PATH!"
    exit 1
fi

mkdir "$TEMP_DIR_NAME" || exit 1
cd "$TEMP_DIR_NAME" || exit 1

# --fail just means to 'fail' silently without a http status code
if ! curl --silent --fail "$PROFILE_REMOTE_URL" -o "$PROFILE_FILE_NAME"; then
    echo "${PROGRAM_NAME}: could not fetch $PROFILE_FILE_NAME from url!"
    exit 1
fi

# shellcheck disable=SC1090
source "./${PROFILE_FILE_NAME}"
rm "./${PROFILE_FILE_NAME}"
cd ..
rmdir "$TEMP_DIR_NAME"

if [ -z "$GIT_REPOS_PATH" ]; then
    echo "${PROGRAM_NAME}: \$GIT_REPOS_PATH was not imported from .profile"
    exit 1
elif ! [ -d "$GIT_REPOS_PATH" ]; then 
    mkdir -p "$GIT_REPOS_PATH"
fi

LOCAL_REPO_PATH="${GIT_REPOS_PATH}/${DOTFILES_REPO_NAME}"

# shellcheck disable=2034
read -r -e -p "Is this a reinstall, y/n? (n) " RE_INSTALL_REPLY <&1

# using parameter expansion, ',,' append will convert the string to lowercase
if [ "${RE_INSTALL_REPLY,,}" == "y" ]; then
    if ! [ -d "$LOCAL_REPO_PATH" ]; then
        echo "$ERROR the $DOTFILES_REPO_NAME cannot be found on the local file system"
        exit 1
    fi
    rm -rf "$LOCAL_REPO_PATH"
fi

git clone --quiet "$DOTFILES_REMOTE_REPO_URL" "$LOCAL_REPO_PATH" > /dev/null
# it is assumed all dotfiles will exist in the same directory (e.g. $HOME)
for dotfile in "${DOTFILES_TO_INCLUDE_FOR_LINKING[@]}"; do
    ln -sf "$LOCAL_REPO_PATH/$dotfile" "./$dotfile"
done

echo -e "$SUCCESS 'install' was successfull! Restart your shell session to pull in new configurations"
